### ISSUE TITLE
Potentially add a config file

### ISSUE THREAD

**Issue by CosmicHorrorDev** [Aloso/to-html#16]
There are several configuration knobs that I would want turned the same way every time I run `to-html`. Adding it as a shell alias can achieves the same effect, but doesn't really seem as nice for more complex configuration

This also opens the door to more easily handling more complex configuration

**Comment by Aloso** [comment]
That's good idea. You can find the configuration directory with <code>[dirs_next](https://docs.rs/dirs-next/latest/dirs_next/index.html)::[config_dir](https://docs.rs/dirs-next/latest/dirs_next/fn.config_dir.html)</code>. The config should probably be written in toml, which is possible with the [`toml`](https://docs.rs/toml/latest/toml/) crate.

Here's a suggestion for the format:

```toml
[shell]
program = "bash"

[output]
cwd = false
full_document = false
highlight = []
css_prefix = ""
```

Does that work for you?
