### ISSUE TITLE
allow mapping color palette

### ISSUE THREAD

**Issue by bend-n** [Aloso/to-html#23]
expose some way of instead of using the default color.
so i can change green (etc) to be light green, or even a completely different color.
currently i can just `.replace("#color", "#color")` but yeah..

may i suggest a option to instead of `style="color:#fff"`, `class="white"`

**Comment by bend-n** [comment]
never mind it seems that you can use a style sheet

**Comment by bend-n** [comment]
never never mind it seems the style sheet thing is for like "terminal" styling

**Comment by CosmicHorrorDev** [comment]
I've actually been meaning to open an issue about this same feature! (It's one of the reasons I wanted a `to-html` config file)

My use case is that currently the styling will generate something like this

```bash
$ to-html 'ls --color'
```

```html
<pre class="terminal">
<span class='shell'>&gt; </span><span class='cmd'>ls</span> <span class='flag'>--color</span>
file.txt  <b><span style='color:#00a'>dir</span></b>
<span class='shell'>&gt; </span><span class='caret'> </span>
</pre>
```

where the color blue is hard-coded through `<span style='color:#00a'>`. For my use case I would like it to be `<span class='term-blue`> instead

I was thinking that we could handle all the 4-bit colors by adding a section to the config like so

```toml
[color]  # alias for [colour] as well
black.attr = "<attr-value>"
# The same for all other 4-bit colors
```

So I could handle the above by setting

```toml
[color]
black.class = "term-black"
red.class = "term-red"
# ...
bright-black.class = "term-bright-black"
bright-red.class = "term-bright-red"
# ...
```

This doesn't handle 8 or 24 bit colors, but it seems so much less likely that someone would want to customize them that I think we could just kick the can on handling it. Could probably be something like

```toml
[color]
eight_bit = [
    ["16", { attr = "<attr-value>" }],
    # ...
]
```
